<<<<<<< Updated upstream
# Generated by Django 4.2.6 on 2023-10-22 16:10

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 5.0 on 2023-12-05 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
>>>>>>> Stashed changes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('informacion', models.CharField(max_length=500)),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('puntos', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialViajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_viajes', to=settings.AUTH_USER_MODEL)),
                ('paquete_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_viajes', to='nosApi.paqueteturistico')),
<<<<<<< Updated upstream
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_viajes', to='nosApi.usuario')),
=======
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to=settings.AUTH_USER_MODEL)),
>>>>>>> Stashed changes
            ],
        ),
    ]
