# Generated by Django 4.2.6 on 2023-10-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
